language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t ekim8/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true ekim8/docker-react npm run test

