language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t ekim8/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true ekim8/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-651152354350"
    bucket: "docker"
    on: 
        branch: master
    access_key_id: $AWS_SECRET_KEY
    secret_access_key: 
        secure: "$AWS_ACCESS_KEY"

